#Should we destroy the environment?
Destroy: true
#Power of the TNT blast.
Power: 5
#Delay in seconds before the egg explodes.
Delay: 0
#How long before the player can throw again? (In seconds)
Cooldown: 10
#Set cost to 0 to disable economy support.
Cost: 0